platform :ios, '8.0'

target 'CJWB' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  
  use_frameworks!

pod 'SDWebImage'
pod 'Alamofire'
pod 'SVProgressHUD'
pod 'SnapKit'
pod 'MJRefresh'

end
